net.ipv4.ip_local_reserved_ports=65330
# Improve consistency and throughput
# https://learn.microsoft.com/en-us/azure/virtual-network/virtual-network-optimize-network-bandwidth?toc=%2Fazure%2Fvirtual-machines%2Ftoc.json#achieving-consistent-transfer-speeds-in-linux-vms-in-azure
net.ipv4.tcp_congestion_control = bbr
# Packet processing in Azure is improved by setting the default qdisc to fq
net.core.default_qdisc = fq